### ISSUE TITLE
Fastmcp server completely crashes When client times out

### ISSUE THREAD

**Issue by yangchangping** [jlowin/fastmcp#823]
### Description

I built a healthy check server tool using FastMCP that simulates stream processing. When a client calls this tool, my issues are as follows:

1、When manually canceling the client process (Ctrl+C) during an incomplete call, the client process exits. At this point, the server cannot detect that the client has exited, and continues to push progress information until the server's s_num reaches its maximum value and actively exits. The server shows no exceptions and can still return normally to subsequent client requests.
2、When setting a client timeout (e.g., 5 seconds) during a call, the client times out and exits. At this point, the server reports a ClosedResourceError exception. After catching the exception, the healthy check continues to run and can print the "healthycheck finished" log. When returning, it reports another ClosedResourceError exception, causing the entire server to crash. Subsequent client requests then fail with the error: "FastMCP's StreamableHTTPSessionManager task group was not initialized".
My first question is: Are the two issues above bugs or problems in my code? My second question is: Can the server detect that the client has exited? If it can detect this, how can the server exit stably without crashing the entire service?

### Example Code

```Python
#server code
import anyio
from fastmcp import FastMCP, Context
# Create an MCP server
mcp = FastMCP(name="tuwenmcpServer",log_level="DEBUG")

@mcp.tool()
async def healthycheck(interval_seconds: int, ctx: Context) -> str:
    s_num=0
    while True:
        await anyio.sleep(interval_seconds)
        s_num=s_num+1
        if s_num<30:
            try:
                await ctx.report_progress(progress=2, total=2, message=f'healthycheck processs {s_num}')
                print("healthycheck server process", s_num)
            except (anyio.ClosedResourceError, anyio.BrokenResourceError) as e:
                print("fastmcp Client disconnected, stopping healthycheck status push.")
                break
            except Exception as e:
                print("Client disconnected, can't status push")
                break
        else:
            break

    print("healthycheck finished")
    return ""

if __name__ == '__main__':
    mcp.run(transport="streamable-http", host="0.0.0.0", port=8001, path="/messages")

#client code
import asyncio
from fastmcp import Client, Context
from fastmcp.client.transports import StreamableHttpTransport
from fastmcp.client.logging import LogMessage

async def log_handler(message: LogMessage):
    level = message.level.upper()
    loggerdata = message.logger or 'default'
    data = message.data
    print(f"[Server Log - {level}] {loggerdata}: {data}")

async def streamableHealthyCheck(timeinterval):
    async with Client(StreamableHttpTransport("http://127.0.0.1:8001/messages/"),
                      log_handler=log_handler) as client:

        tools = await client.list_tools()
        print(f'cvpro tools: {tools}')

        try:
            async def healthy_handler(
                    progress: float,
                    total: float | None,
                    message: str | None
            ) -> None:
                print(f"{message}")

            result = await client.call_tool(
                "healthycheck",
                arguments={"interval_seconds": timeinterval},
                progress_handler=healthy_handler,
                timeout=5
            )
            print(f"healthycheck finished: \n, {result[0].text}")
        except Exception as e:
            print(f"healthycheck error： {str(e)}")
            # await client.close()

if __name__ == '__main__':
    asyncio.run(streamableHealthyCheck(5))
```

### Version Information

```Text
fastmcp 2.8.0
```

### Additional Context

here is server logs when client time out
[06/13/25 10:48:01] INFO     Starting MCP server 'tuwenmcpServer' server.py:1210
                             with transport 'streamable-http' on                
                             http://0.0.0.0:8001/messages                       
INFO:     Started server process [55842]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
INFO:     127.0.0.1:62348 - "POST /messages/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:62351 - "POST /messages/ HTTP/1.1" 202 Accepted
INFO:     127.0.0.1:62352 - "GET /messages/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:62354 - "POST /messages/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:62356 - "POST /messages/ HTTP/1.1" 200 OK
[06/13/25 10:48:05] DEBUG    Call tool: healthycheck with          server.py:518
                             {'interval_seconds': 5}                            
INFO:     127.0.0.1:62404 - "DELETE /messages/ HTTP/1.1" 200 OK
fastmcp Client disconnected, stopping healthycheck status push.
healthycheck finished
ERROR:    Traceback (most recent call last):
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/streamable_http_manager.py", line 111, in run
    yield  # Let the application run
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/fastmcp/server/http.py", line 346, in lifespan
    yield
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/starlette/routing.py", line 739, in lifespan
    await receive()
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1071eeb30

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/starlette/routing.py", line 730, in lifespan
  |     async with self.lifespan_context(app) as maybe_state:
  |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/contextlib.py", line 217, in __aexit__
  |     await self.gen.athrow(typ, value, traceback)
  |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/fastmcp/server/http.py", line 345, in lifespan
  |     async with session_manager.run():
  |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/contextlib.py", line 217, in __aexit__
  |     await self.gen.athrow(typ, value, traceback)
  |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/streamable_http_manager.py", line 106, in run
  |     async with anyio.create_task_group() as tg:
  |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/streamable_http.py", line 919, in connect
    |     yield read_stream, write_stream
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/streamable_http_manager.py", line 238, in run_server
    |     await self.app.run(
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/lowlevel/server.py", line 500, in run
    |     async with AsyncExitStack() as stack:
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/contextlib.py", line 714, in __aexit__
    |     raise exc_details[1]
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/contextlib.py", line 217, in __aexit__
    |     await self.gen.athrow(typ, value, traceback)
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/fastmcp/server/server.py", line 106, in wrap
    |     yield context
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/contextlib.py", line 697, in __aexit__
    |     cb_suppress = await cb(*exc_details)
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/shared/session.py", line 223, in __aexit__
    |     return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
    |     raise BaseExceptionGroup(
    | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/lowlevel/server.py", line 511, in run
      |     async with anyio.create_task_group() as tg:
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
      |     raise BaseExceptionGroup(
      | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
      +-+---------------- 1 ----------------
        | Traceback (most recent call last):
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/lowlevel/server.py", line 539, in _handle_message
        |     await self._handle_request(
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/lowlevel/server.py", line 594, in _handle_request
        |     await message.respond(response)
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/shared/session.py", line 134, in respond
        |     await self._session._send_response(  # type: ignore[reportPrivateUsage]
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/shared/session.py", line 346, in _send_response
        |     await self._write_stream.send(session_message)
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/streams/memory.py", line 242, in send
        |     self.send_nowait(item)
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/streams/memory.py", line 211, in send_nowait
        |     raise ClosedResourceError
        | anyio.ClosedResourceError
        +------------------------------------
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Exception Group Traceback (most recent call last):
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/streamable_http_manager.py", line 235, in run_server
    |     async with http_transport.connect() as streams:
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/contextlib.py", line 217, in __aexit__
    |     await self.gen.athrow(typ, value, traceback)
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/streamable_http.py", line 846, in connect
    |     async with anyio.create_task_group() as tg:
    |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
    |     raise BaseExceptionGroup(
    | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/lowlevel/server.py", line 511, in run
      |     async with anyio.create_task_group() as tg:
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
      |     raise BaseExceptionGroup(
      | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
      +-+---------------- 1 ----------------
        | Traceback (most recent call last):
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/lowlevel/server.py", line 539, in _handle_message
        |     await self._handle_request(
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/lowlevel/server.py", line 594, in _handle_request
        |     await message.respond(response)
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/shared/session.py", line 134, in respond
        |     await self._session._send_response(  # type: ignore[reportPrivateUsage]
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/shared/session.py", line 346, in _send_response
        |     await self._write_stream.send(session_message)
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/streams/memory.py", line 242, in send
        |     self.send_nowait(item)
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/streams/memory.py", line 211, in send_nowait
        |     raise ClosedResourceError
        | anyio.ClosedResourceError
        +------------------------------------
      | 
      | During handling of the above exception, another exception occurred:
      | 
      | Exception Group Traceback (most recent call last):
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/streamable_http.py", line 919, in connect
      |     yield read_stream, write_stream
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/streamable_http_manager.py", line 238, in run_server
      |     await self.app.run(
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/lowlevel/server.py", line 500, in run
      |     async with AsyncExitStack() as stack:
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/contextlib.py", line 714, in __aexit__
      |     raise exc_details[1]
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/contextlib.py", line 217, in __aexit__
      |     await self.gen.athrow(typ, value, traceback)
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/fastmcp/server/server.py", line 106, in wrap
      |     yield context
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/contextlib.py", line 697, in __aexit__
      |     cb_suppress = await cb(*exc_details)
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/shared/session.py", line 223, in __aexit__
      |     return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
      |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
      |     raise BaseExceptionGroup(
      | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
      +-+---------------- 1 ----------------
        | Exception Group Traceback (most recent call last):
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/lowlevel/server.py", line 511, in run
        |     async with anyio.create_task_group() as tg:
        |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
        |     raise BaseExceptionGroup(
        | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
        +-+---------------- 1 ----------------
          | Traceback (most recent call last):
          |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/lowlevel/server.py", line 539, in _handle_message
          |     await self._handle_request(
          |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/lowlevel/server.py", line 594, in _handle_request
          |     await message.respond(response)
          |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/shared/session.py", line 134, in respond
          |     await self._session._send_response(  # type: ignore[reportPrivateUsage]
          |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/shared/session.py", line 346, in _send_response
          |     await self._write_stream.send(session_message)
          |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/streams/memory.py", line 242, in send
          |     self.send_nowait(item)
          |   File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/anyio/streams/memory.py", line 211, in send_nowait
          |     raise ClosedResourceError
          | anyio.ClosedResourceError
          +------------------------------------

INFO:     127.0.0.1:65366 - "POST /messages/ HTTP/1.1" 500 Internal Server Error
[06/13/25 10:54:37] ERROR    Original RuntimeError from mcp library: http.py:288
                             Task group is not initialized. Make                
                             sure to use run().                                 
                             ╭─ Traceback (most recent call last) ─╮            
                             │ /Users/yangchangping/anaconda3/envs │            
                             │ /mcp-dev/lib/python3.10/site-packag │            
                             │ es/fastmcp/server/http.py:285 in    │            
                             │ handle_streamable_http              │            
                             │                                     │            
                             │   282 │   │   scope: Scope, receive │            
                             │   283 │   ) -> None:                │            
                             │   284 │   │   try:                  │            
                             │ ❱ 285 │   │   │   await session_man │            
                             │   286 │   │   except RuntimeError a │            
                             │   287 │   │   │   if str(e) == "Tas │            
                             │   288 │   │   │   │   logger.error( │            
                             │                                     │            
                             │ /Users/yangchangping/anaconda3/envs │            
                             │ /mcp-dev/lib/python3.10/site-packag │            
                             │ es/mcp/server/streamable_http_manag │            
                             │ er.py:137 in handle_request         │            
                             │                                     │            
                             │   134 │   │   │   send: ASGI send f │            
                             │   135 │   │   """                   │            
                             │   136 │   │   if self._task_group i │            
                             │ ❱ 137 │   │   │   raise RuntimeErro │            
                             │   138 │   │                         │            
                             │   139 │   │   # Dispatch to the app │            
                             │   140 │   │   if self.stateless:    │            
                             ╰─────────────────────────────────────╯            
                             RuntimeError: Task group is not                    
                             initialized. Make sure to use run().               
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/fastmcp/server/http.py", line 285, in handle_streamable_http
    await session_manager.handle_request(scope, receive, send)
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/mcp/server/streamable_http_manager.py", line 137, in handle_request
    raise RuntimeError("Task group is not initialized. Make sure to use run().")
RuntimeError: Task group is not initialized. Make sure to use run().

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/fastmcp/server/http.py", line 67, in __call__
    await self.app(scope, receive, send)
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/starlette/routing.py", line 483, in handle
    await self.app(scope, receive, send)
  File "/Users/yangchangping/anaconda3/envs/mcp-dev/lib/python3.10/site-packages/fastmcp/server/http.py", line 303, in handle_streamable_http
    raise RuntimeError(f"{new_error_message}\\nOriginal error: {e}") from e
RuntimeError: FastMCP's StreamableHTTPSessionManager task group was not initialized. This commonly occurs when the FastMCP application's lifespan is not passed to the parent ASGI application (e.g., FastAPI or Starlette). Please ensure you are setting `lifespan=mcp_app.lifespan` in your parent app's constructor, where `mcp_app` is the application instance returned by `fastmcp_instance.http_app()`. \nFor more details, see the FastMCP ASGI integration documentation: https://gofastmcp.com/deployment/asgi\nOriginal error: Task group is not initialized. Make sure to use run()

**Comment by Sillocan** [comment]
What version of FastMCP and mcp are you using? There was an issue with uncaught exceptions locking the server that was addressed in mcp==1.9.4

**Comment by yangchangping** [comment]
> What version of FastMCP and mcp are you using? There was an issue with uncaught exceptions locking the server that was addressed in mcp==1.9.4

The version of fastmcp I'm using is 2.8.0, and I'm not using mcp. Which  issue of mcp 1.9.4 are you referring to? Could you please provide the link so that I can check if it's the same problem?

**Comment by Sillocan** [comment]
> > What version of FastMCP and mcp are you using? There was an issue with uncaught exceptions locking the server that was addressed in mcp==1.9.4
> 
> The version of fastmcp I'm using is 2.8.0, and I'm not using mcp. Which issue of mcp 1.9.4 are you referring to? Could you please provide the link so that I can check if it's the same problem?

Can you try updating to 2.8.1 of FastMCP?

`mcp` is a dependency of FastMCP

**Comment by yangchangping** [comment]
> > > What version of FastMCP and mcp are you using? There was an issue with uncaught exceptions locking the server that was addressed in mcp==1.9.4
> > 
> > 
> > The version of fastmcp I'm using is 2.8.0, and I'm not using mcp. Which issue of mcp 1.9.4 are you referring to? Could you please provide the link so that I can check if it's the same problem?
> 
> Can you try updating to 2.8.1 of FastMCP?
> 
> `mcp` is a dependency of FastMCP

I tried version 2.8.1, and the same issue still occurred. The code I provided can reproduce the problem.

**Comment by Sillocan** [comment]
Interesting, I see.

**Comment by yangchangping** [comment]
> Interesting, I see.

looking forward to both temporary and thorough solutions  😊

**Comment by randyzhongnb** [comment]
I got similar cashes with this one.  Any suggestion to this issue ?

**Comment by yangchangping** [comment]
> I got similar cashes with this one. Any suggestion to this issue ?

Based on my experience, if streaming response isn't required, you can configure it like this:
mcp = FastMCP(name="testServer", stateless_http=True). In this scenario, the server won't crash when the client times out.
If streaming responses are required, we'll have to wait until this issue is resolved.

**Comment by randyzhongnb** [comment]
> > I got similar cashes with this one. Any suggestion to this issue ?
> 
> Based on my experience, if streaming response isn't required, you can configure it like this: mcp = FastMCP(name="testServer", stateless_http=True). In this scenario, the server won't crash when the client times out. If streaming responses are required, we'll have to wait until this issue is resolved.

Works in my case. Thanks!

**Comment by Kamal-Moha** [comment]
Hi @yangchangping I have tried your suggested approach but still getting an issue when I try using the server. He is how I have create the FastMCP Server

```python
from fastmcp import FastMCP

app = FastMCP(name="testServer", stateless_http=True)

@app.tool()
def add(a: int, b: int) -> int:
    return a + b

if __name__ == '__main__':
    app.run(
        transport="http",
        host="127.0.0.1",
        port=8000,
        path="/mcp",
        log_level="debug",
    )
```

When I try using it, I get the below error;
`asyncio.exceptions.CancelledError: Cancelled by cancel scope 14fd2dbfb90
`
Is there anything I'm doing wrong?
